apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: frontend-stage
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stage.klimatkollen.se
      secretName: stage-klimatkollen-se-tls
  rules:
    - host: stage.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                namespace: frontend-stage
                port:
                  number: 80
