name: Continuous Integration

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - "k8s/**"

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Install dependencies and update lock file
        run: |
          rm -rf node_modules package-lock.json  # Ensure fresh install
          npm install --legacy-peer-deps
          npm rebuild

      - name: 🛠️ Commit `package-lock.json` if changed
        run: |
          if [[ `git status --porcelain package-lock.json` ]]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add package-lock.json
            git commit -m "Update package-lock.json [skip ci]"
            git push origin main
          else
            echo "No changes in package-lock.json"
          fi

      - name: 📌 Show Node.js & NPM versions
        run: |
          node -v
          npm -v
          npx vite -v
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          progress: false

      - name: 🎫 Update patch version
        run: |
          git fetch
          git checkout main
          git pull origin main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [[ $GITHUB_REF == refs/tags/production* ]]; then
            npm version major
          elif [[ $GITHUB_REF == refs/tags/staging* ]]; then
            npm version minor
          else
            npm version patch
          fi
          git fetch --all
          git push origin main

  ci:
    runs-on: ubuntu-latest
    needs: version

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - id: imagename
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [[ $GITHUB_REF == refs/tags/production* ]]; then
            npm version major
          elif [[ $GITHUB_REF == refs/tags/staging* ]]; then
            npm version minor
          else
            npm version patch
          fi

      - name: 📝 Get Current Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: 🔐 Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔧 Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase  }}:${{ steps.package-version.outputs.current-version}}
